openapi: 3.2.0
info:
  title: Salv Aml API
  description: '# Introduction

    Welcome to the Salv AML API documentation.


    The Salv API is built on HTTP. Our API is RESTful. It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. You can use your favorite HTTP/REST library for your programming language to use Salv API.


    API definition to import into Postman can be downloaded at https://docs.salv.com/api/public.yaml'
  version: 1.0.9
  contact:
    name: Support
    email: support@salv.com
  x-logo:
    url: salv.svg
    altText: Salv API
servers:
- url: https://{environment}.salv.com/api/
  variables:
    environment:
      default: app
      enum:
      - app
      - demo
      description: 'Select environment:

        * `app` - Production

        * `demo` - Sandbox

        '
security:
- OAuth2:
  - aml
tags:
- name: AML
  x-displayName: Persons & Transactions
  description: This section contains all operations managing the state of persons and transactions.
paths:
  /v2/persons:
    post:
      tags:
      - AML
      summary: Create new person
      description: Attributes supported maximum nesting depth is 2.
      operationId: addPersonV2
      x-codeSamples:
      - lang: curl
        label: cURL
        source: "curl -X POST \"https://app.salv.com/api/v2/persons\" \\\n  -H \"Authorization: Bearer $ACCESS_TOKEN\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n    \"id\": \"person-123\",\n    \"type\": \"INDIVIDUAL\",\n    \"attributes\": {\n      \"first_name\": \"John\",\n      \"last_name\": \"Doe\",\n      \"dob\": \"1990-01-15\",\n      \"country\": \"US\"\n    }\n  }'\n"
      - lang: Python
        source: "import requests\n\nresponse = requests.post(\n    \"https://app.salv.com/api/v2/persons\",\n    headers={\"Authorization\": f\"Bearer {access_token}\"},\n    json={\n        \"id\": \"person-123\",\n        \"type\": \"INDIVIDUAL\",\n        \"attributes\": {\n            \"first_name\": \"John\",\n            \"last_name\": \"Doe\",\n            \"dob\": \"1990-01-15\",\n            \"country\": \"US\"\n        }\n    }\n)\n"
      - lang: JavaScript
        label: Node.js
        source: "const response = await fetch(\"https://app.salv.com/api/v2/persons\", {\n  method: \"POST\",\n  headers: {\n    \"Authorization\": `Bearer ${accessToken}`,\n    \"Content-Type\": \"application/json\"\n  },\n  body: JSON.stringify({\n    id: \"person-123\",\n    type: \"INDIVIDUAL\",\n    attributes: {\n      first_name: \"John\",\n      last_name: \"Doe\",\n      dob: \"1990-01-15\",\n      country: \"US\"\n    }\n  })\n});\n"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/ApiCreatePersonV2
            examples:
              Individual:
                value:
                  id: bbt12345
                  type: INDIVIDUAL
                  attributes:
                    first_name: Sheldon
                    last_name: Cooper
                    dob: '1983-05-12'
                    city: Pasadena
                    street_address: 2311 North Los Robles Avenue
                    country: US
                    onboarding_date: '2019-04-16T11:10:55.123456Z'
                    email: sheldon.cooper@gmail.com
                    phone_number: '+1582693582'
                    id_document: passport
                    id_country: US
                    gender: F
              Individual_with_nested_attributes:
                value:
                  id: bbt12345
                  type: INDIVIDUAL
                  attributes:
                    first_name: Sheldon
                    last_name: Cooper
                    dob: '1983-05-12'
                    city: Pasadena
                    street_address: 2311 North Los Robles Avenue
                    country: US
                    onboarding_date: '2019-04-16T11:10:55.123456Z'
                    email: sheldon.cooper@gmail.com
                    phone_number: '+1582693582'
                    id_document: passport
                    id_country: US
                    gender: F
                    contracts:
                    - id: 1
                      loan_type: loan_agreement
                      status: active
                      start_date: '2022-01-20T08:48:39Z'
                    - id: 2
                      loan_type: lease
                      status: inactive
                      start_date: '2020-01-20T08:48:39Z'
                      end_date: '2022-01-20T08:48:39Z'
              Legal:
                value:
                  id: bbt12346
                  type: LEGAL
                  attributes:
                    company_name: The Cheesecake factory
                    onboarding_date: '2020-06-12T11:10:55.123456Z'
                    country: FR
                    city: Pasadena
                    street_address: 2311 North Los Robles Avenue
                    email: info@cheescakefactory.com
                    phone_number: '+1472583692'
                    industry: restaurant
                    business_reg_number: 12-3456789
                    expected_monthly_turnover: '100000'
              Legal_with_nested_attributes:
                value:
                  id: bbt12347
                  type: LEGAL
                  attributes:
                    company_name: Footprints on the Moon
                    onboarding_date: '2021-05-24T11:10:55.123456Z'
                    country: CA
                    city: Pasadena
                    street_address: 2311 North Los Robles Avenue
                    email: footprintsonthemoon@gmail.com
                    phone_number: '+1582472952'
                    industry: entertainment
                    shareholders:
                    - id: shrhldr-1
                      first_name: Howard
                      last_name: Wolowitz
                      dob: '1988-07-06'
                      citizenship: IL
                    - id: shrhldr-2
                      first_name: Raj
                      last_name: Koothrappali
                      dob: '1989-05-06'
                      citizenship: IN
                    - id: shrhldr-3
                      company_name: BIG Invest LLC
                      country: GB
                    business_reg_number: 98-7654321
                    expected_monthly_turnover: '10000'
      responses:
        '200':
          description: Created person
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '422':
          description: Person exists
  /v2/persons/search:
    post:
      tags:
      - AML
      summary: Fetch all persons
      operationId: findAllPersons
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/ApiPersonSearchQuery
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/PersonsPage
  /v2/persons/{personId}:
    patch:
      tags:
      - AML
      summary: Patch person
      description: 'Partial person update. Only attributes present in request will be added/updated. Attributes supported maximum

        nesting depth is 2.


        This endpoint also supports optional person type update.


        In case the operation is successful there will be an empty response.


        ### Examples

        #### cURL

        ```

        $ curl --request PATCH \

        --url https://app.salv.com/api/v2/persons/{personId} \

        --header ''Authorization: Bearer {yourBearerToken}'' \

        --header ''Content-Type: application/json'' \

        --data ''{

        "type": "LEGAL",

        "attributes": {

        "company_name": "Best Vacuum Cleaning Ltd."

        }

        }''

        ```


        #### With Python Requests

        ```

        import requests


        payload = {

        "attributes": {

        "phone_number": "(198)747-8241x9209",

        "shareholders": [{

        "id": 1,

        "name": "Rose Doe",

        "dob": "1970-01-01",

        "email": "rose.doe@gmail.com"

        }]

        }

        }


        response = requests.post(

        ''https://app.salv.com/api/v2/persons/{personId}'',

        auth = ({clientId}, {clientSecret}),

        json = payload)


        response.raise_for_status()

        ```'
      operationId: patchPersonV2
      parameters:
      - name: personId
        in: path
        description: External unique person ID
        required: true
        schema:
          type: string
          minLength: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/ApiPatchPersonV2
            examples:
              Individual:
                value:
                  attributes:
                    last_name: Doe
                    dob: '1970-01-01'
              Legal:
                value:
                  attributes:
                    phone_number: (198)747-8241x9209
                    shareholders:
                    - id: 1
                      name: Rose Doe
                      dob: '1970-01-01'
                      email: rose.doe@gmail.com
              TypeChange:
                value:
                  type: LEGAL
                  attributes:
                    companyName: Very Good Vacuum Cleaning Ltd.
      responses:
        '200':
          description: Successfully updated person
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Person not found
    put:
      tags:
      - AML
      summary: Update person
      description: 'Person update. Attributes in the request will be used to replace existing ones and type will be updated.

        Attributes supported maximum nesting depth is 2.


        In case the operation is successful there will be an empty response.


        ### Examples

        #### cURL

        ```

        $ curl --request PUT \

        --url https://app.salv.com/api/v2/persons/{personId} \

        --header ''Authorization: Bearer {yourBearerToken}'' \

        --header ''Content-Type: application/json'' \

        --data ''{

        "type": "LEGAL",

        "attributes": {

        "company_name": "Best Vacuum Cleaning Ltd."

        }

        }''

        ```


        #### With Python Requests

        ```

        import requests


        payload = {

        "type": "INDIVIDUAL",

        "attributes": {

        "phone_number": "(198)747-8241x9209",

        "shareholders": [{

        "id": 1,

        "name": "Rose Doe",

        "dob": "1970-01-01",

        "email": "rose.doe@gmail.com"

        }]

        }

        }


        response = requests.post(

        ''https://app.salv.com/api/v2/persons/{personId}'',

        auth = ({clientId}, {clientSecret}),

        json = payload)


        response.raise_for_status()

        ```'
      operationId: updatePersonV2
      parameters:
      - name: personId
        in: path
        description: External unique person ID
        required: true
        schema:
          type: string
          minLength: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/ApiUpdatePersonV2
            examples:
              Individual:
                value:
                  type: INDIVIDUAL
                  attributes:
                    last_name: Doe
                    dob: '1970-01-01'
              Legal:
                value:
                  type: LEGAL
                  attributes:
                    phone_number: (198)747-8241x9209
                    shareholders:
                    - id: 1
                      name: Rose Doe
                      dob: '1970-01-01'
                      email: rose.doe@gmail.com
      responses:
        '200':
          description: Updated person
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Person not found
  /v1/persons:
    get:
      deprecated: true
      tags:
      - AML
      summary: Fetch all persons
      operationId: findAllPersonsDeprecated
      description: NB! If there are more than 10000 results then the API shows the number of total results as 10000 and you can't paginate past the 10000th result.
      parameters:
      - $ref: models.yaml#/components/parameters/pageParam
      - $ref: models.yaml#/components/parameters/sizeParam
      - $ref: models.yaml#/components/parameters/queryParam
      - name: attribute
        in: query
        description: Search query attribute
        required: false
        schema:
          type: string
          minLength: 1
      - name: category
        in: query
        description: Person category
        required: false
        schema:
          type: string
          enum:
          - COUNTERPARTY
          - CUSTOMER
      - $ref: models.yaml#/components/parameters/orderByParam
      - $ref: models.yaml#/components/parameters/orderDirectionParam
      - $ref: models.yaml#/components/parameters/searchOperator
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/PersonsPage
              examples:
                result:
                  value:
                    number: 0
                    size: 20
                    total: 1
                    content:
                    - id: bbt12345
                      type: INDIVIDUAL
                      attributes:
                        first_name: Sheldon
                        last_name: Cooper
                        dob: '1983-05-12'
                        city: Pasadena
                        street_address: 2311 North Los Robles Avenue
                        country: US
                        onboarding_date: '2019-04-16'
                        email: sheldon.cooper@gmail.com
                        phone_number: '+1582693582'
                        id_document: passport
                        id_country: US
                        gender: F
                      status: NEW
                      createdTime: '2019-08-24T14:15:22Z'
                      snoozeConfiguration:
                        id: 1
                        personId: 1
                        createdBy:
                          id: 1
                          email: dana.aml@starbank.com
                          name: Dana Cummings
                        createdTime: '2019-08-24T14:15:22Z'
                        endTime: '2019-08-24T14:15:22Z'
                        amount: 0
                        totalAmount: 0
                        note: {}
                      category: CUSTOMER
    post:
      tags:
      - AML
      summary: Create new person (v1)
      description: Use Create new person v2 instead.
      operationId: addPerson
      deprecated: true
      requestBody:
        required: true
        content:
          application/json:
            examples:
              Individual:
                value:
                  id: bbt12345
                  type: INDIVIDUAL
                  attributes:
                    first_name: Sheldon
                    last_name: Cooper
                    dob: '1983-05-12'
                    city: Pasadena
                    street_address: 2311 North Los Robles Avenue
                    country: US
                    onboarding_date: '2019-04-16T11:10:55.123456Z'
                    email: sheldon.cooper@gmail.com
                    phone_number: '+1582693582'
                    id_document: passport
                    id_country: US
                    gender: F
              Legal:
                value:
                  id: bbt12346
                  type: LEGAL
                  attributes:
                    company_name: The Cheesecake factory
                    onboarding_date: '2020-06-12T11:10:55.123456Z'
                    country: FR
                    city: Pasadena
                    street_address: 2311 North Los Robles Avenue
                    email: info@cheescakefactory.com
                    phone_number: '+1472583692'
                    industry: restaurant
                    business_reg_number: 12-3456789
                    expected_monthly_turnover: '100000'
            schema:
              $ref: models.yaml#/components/schemas/ApiCreatePerson
      responses:
        '200':
          description: Created person
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/ApiPerson
              examples:
                Individual:
                  value:
                    id: bbt12345
                    type: INDIVIDUAL
                    attributes:
                      first_name: Sheldon
                      last_name: Cooper
                      dob: '1983-05-12'
                      city: Pasadena
                      street_address: 2311 North Los Robles Avenue
                      country: US
                      onboarding_date: '2019-04-16'
                      email: sheldon.cooper@gmail.com
                      phone_number: '+1582693582'
                      id_document: passport
                      id_country: US
                      gender: F
                Legal:
                  value:
                    id: bbt12346
                    type: LEGAL
                    attributes:
                      company_name: The Cheesecake factory
                      onboarding_date: '2020-06-12'
                      country: FR
                      city: Pasadena
                      street_address: 2311 North Los Robles Avenue
                      email: info@cheescakefactory.com
                      phone_number: '+1472583692'
                      industry: restaurant
                      business_reg_number: 12-3456789
                      expected_monthly_turnover: '100000'
        '400':
          description: Bad request
          content:
            application/text:
              schema:
                type: string
                description: Error message
        '401':
          description: Unauthorized
          content:
            application/text:
              schema:
                type: string
                description: Error message
        '422':
          description: Person exists
          content:
            application/text:
              schema:
                type: string
                description: Error message
  /v1/persons/{personId}:
    get:
      tags:
      - AML
      summary: Fetch person by id
      operationId: findPersonById
      x-codeSamples:
      - lang: curl
        label: cURL
        source: "curl -X GET \"https://app.salv.com/api/v1/persons/bbt12345\" \\\n  -H \"Authorization: Bearer $ACCESS_TOKEN\"\n"
      - lang: Python
        source: "import requests\n\nperson_id = \"bbt12345\"\nresponse = requests.get(\n    f\"https://app.salv.com/api/v1/persons/{person_id}\",\n    headers={\"Authorization\": f\"Bearer {access_token}\"}\n)\nperson = response.json()\n"
      - lang: JavaScript
        label: Node.js
        source: "const personId = \"bbt12345\";\nconst response = await fetch(\n  `https://app.salv.com/api/v1/persons/${personId}`,\n  {\n    headers: { \"Authorization\": `Bearer ${accessToken}` }\n  }\n);\nconst person = await response.json();\n"
      parameters:
      - name: personId
        in: path
        description: ID of person to return
        required: true
        schema:
          type: string
          minLength: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/ApiPerson
              examples:
                Individual:
                  value:
                    id: bbt12345
                    type: INDIVIDUAL
                    attributes:
                      first_name: Sheldon
                      last_name: Cooper
                      dob: '1983-05-12'
                      city: Pasadena
                      street_address: 2311 North Los Robles Avenue
                      country: US
                      onboarding_date: '2019-04-16'
                      email: sheldon.cooper@gmail.com
                      phone_number: '+1582693582'
                      id_document: passport
                      id_country: US
                      gender: F
                    status: NEW
                    createdTime: '2019-08-24T14:15:22Z'
                    snoozeConfiguration:
                      id: 1
                      personId: 1
                      createdBy:
                        id: 1
                        email: dana.aml@starbank.com
                        name: Dana Cummings
                      createdTime: '2019-08-24T14:15:22Z'
                      endTime: '2019-08-24T14:15:22Z'
                      amount: 0
                      totalAmount: 0
                      note: {}
                    category: CUSTOMER
                Individual_with_nested_attributes:
                  value:
                    id: bbt12345
                    type: INDIVIDUAL
                    attributes:
                      first_name: Sheldon
                      last_name: Cooper
                      dob: '1983-05-12'
                      city: Pasadena
                      street_address: 2311 North Los Robles Avenue
                      country: US
                      onboarding_date: '2019-04-16'
                      email: sheldon.cooper@gmail.com
                      phone_number: '+1582693582'
                      id_document: passport
                      id_country: US
                      gender: F
                      contracts:
                      - id: 1
                        loan_type: loan_agreement
                        status: active
                        start_date: '2022-01-20T08:48:39Z'
                      - id: 2
                        loan_type: lease
                        status: inactive
                        start_date: '2020-01-20T08:48:39Z'
                        end_date: '2022-01-20T08:48:39Z'
                    status: NEW
                    createdTime: '2019-08-24T14:15:22Z'
                    snoozeConfiguration:
                      id: 1
                      personId: 1
                      createdBy:
                        id: 1
                        email: dana.aml@starbank.com
                        name: Dana Cummings
                      createdTime: '2019-08-24T14:15:22Z'
                      endTime: '2019-08-24T14:15:22Z'
                      amount: 0
                      totalAmount: 0
                      note: {}
                    category: CUSTOMER
                Legal:
                  value:
                    id: bbt12346
                    type: LEGAL
                    attributes:
                      company_name: The Cheesecake factory
                      onboarding_date: '2020-06-12'
                      country: FR
                      city: Pasadena
                      street_address: 2311 North Los Robles Avenue
                      email: info@cheescakefactory.com
                      phone_number: '+1472583692'
                      industry: restaurant
                      business_reg_number: 12-3456789
                      expected_monthly_turnover: '100000'
                    status: NEW
                    createdTime: '2019-08-24T14:15:22Z'
                    snoozeConfiguration:
                      id: 1
                      personId: 1
                      createdBy:
                        id: 1
                        email: dana.aml@starbank.com
                        name: Dana Cummings
                      createdTime: '2019-08-24T14:15:22Z'
                      endTime: '2019-08-24T14:15:22Z'
                      amount: 0
                      totalAmount: 0
                      note: {}
                    category: CUST0MER
                Legal_with_nested_attributes:
                  value:
                    id: bbt12347
                    type: LEGAL
                    attributes:
                      company_name: Footprints on the Moon
                      onboarding_date: '2021-05-24'
                      country: CA
                      city: Pasadena
                      street_address: 2311 North Los Robles Avenue
                      email: footprintsonthemoon@gmail.com
                      phone_number: '+1582472952'
                      industry: entertainment
                      shareholders:
                      - id: shrhldr-1
                        first_name: Howard
                        last_name: Wolowitz
                        dob: '1988-07-06'
                        citizenship: IL
                      - id: shrhldr-2
                        first_name: Raj
                        last_name: Koothrappali
                        dob: '1989-05-06'
                        citizenship: IN
                      - id: shrhldr-3
                        company_name: BIG Invest LLC
                        country: GB
                      business_reg_number: 98-7654321
                      expected_monthly_turnover: '10000'
                    status: NEW
                    createdTime: '2019-08-24T14:15:22Z'
                    snoozeConfiguration:
                      id: 1
                      personId: 1
                      createdBy:
                        id: 1
                        email: dana.aml@starbank.com
                        name: Dana Cummings
                      createdTime: '2019-08-24T14:15:22Z'
                      endTime: '2019-08-24T14:15:22Z'
                      amount: 0
                      totalAmount: 0
                      note: {}
                    category: CUSTOMER
        '400':
          description: Invalid ID supplied
        '404':
          description: Person not found
    patch:
      tags:
      - AML
      summary: Patch person (v1)
      description: Use Patch person v2 instead.
      operationId: updatePerson
      deprecated: true
      parameters:
      - name: personId
        in: path
        description: ID of person to return
        required: true
        schema:
          type: string
          minLength: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/ApiPerson
      responses:
        '200':
          description: Updated person
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/ApiPerson
        '400':
          description: Invalid input
  /v1/persons/{personId}/transactions:
    get:
      tags:
      - AML
      summary: Fetch all person transactions
      description: NB! If there are more than 10000 results then the API shows the number of total results as 10000 and you can't paginate past the 10000th result.
      operationId: findAllPersonTransactions
      parameters:
      - name: personId
        in: path
        description: ID of person
        required: true
        schema:
          type: string
          minLength: 1
      - $ref: models.yaml#/components/parameters/pageParam
      - $ref: models.yaml#/components/parameters/sizeParam
      - $ref: models.yaml#/components/parameters/queryParam
      - $ref: models.yaml#/components/parameters/orderByParam
      - $ref: models.yaml#/components/parameters/orderDirectionParam
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/TransactionsPage
    post:
      tags:
      - AML
      summary: Create new transaction
      operationId: addTransaction
      x-codeSamples:
      - lang: curl
        label: cURL
        source: "curl -X POST \"https://app.salv.com/api/v1/persons/bbt12345/transactions\" \\\n  -H \"Authorization: Bearer $ACCESS_TOKEN\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n    \"id\": \"txn-123\",\n    \"attributes\": {\n      \"sender_name\": \"John Doe\",\n      \"sender_account\": \"GB123456789\",\n      \"receiver_name\": \"Jane Smith\",\n      \"receiver_account\": \"DE987654321\",\n      \"amount\": \"1500.00\",\n      \"type\": \"wire_transfer\",\n      \"direction\": \"O\",\n      \"timestamp\": \"2024-01-20T10:30:00Z\"\n    }\n  }'\n"
      - lang: Python
        source: "import requests\n\nperson_id = \"bbt12345\"\nresponse = requests.post(\n    f\"https://app.salv.com/api/v1/persons/{person_id}/transactions\",\n    headers={\"Authorization\": f\"Bearer {access_token}\"},\n    json={\n        \"id\": \"txn-123\",\n        \"attributes\": {\n            \"sender_name\": \"John Doe\",\n            \"sender_account\": \"GB123456789\",\n            \"receiver_name\": \"Jane Smith\",\n            \"receiver_account\": \"DE987654321\",\n            \"amount\": \"1500.00\",\n            \"type\": \"wire_transfer\",\n            \"direction\": \"O\",\n            \"timestamp\": \"2024-01-20T10:30:00Z\"\n        }\n    }\n)\n"
      - lang: JavaScript
        label: Node.js
        source: "const personId = \"bbt12345\";\nconst response = await fetch(\n  `https://app.salv.com/api/v1/persons/${personId}/transactions`,\n  {\n    method: \"POST\",\n    headers: {\n      \"Authorization\": `Bearer ${accessToken}`,\n      \"Content-Type\": \"application/json\"\n    },\n    body: JSON.stringify({\n      id: \"txn-123\",\n      attributes: {\n        sender_name: \"John Doe\",\n        sender_account: \"GB123456789\",\n        receiver_name: \"Jane Smith\",\n        receiver_account: \"DE987654321\",\n        amount: \"1500.00\",\n        type: \"wire_transfer\",\n        direction: \"O\",\n        timestamp: \"2024-01-20T10:30:00Z\"\n      }\n    })\n  }\n);\n"
      parameters:
      - name: personId
        in: path
        description: ID of person
        required: true
        example: bbt12345
        schema:
          type: string
          minLength: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/ApiCreateTransaction
            examples:
              Between_2_IBANs:
                value:
                  id: aeio-1234567
                  attributes:
                    sender_name: Sheldon Cooper
                    sender_account: GB123456789
                    receiver_name: Leonard Hofstadter
                    receiver_account: DE987654321
                    amount: '15678.34'
                    type: wire_transfer
                    direction: I
                    timestamp: '2022-01-20T08:48:39Z'
              Between_2_BBANs_v1:
                value:
                  id: aeio-1234568
                  attributes:
                    sender_name: Footprints on the Moon
                    sender_account: '123456789'
                    receiver_name: Bernadette Rostenkowski
                    receiver_account: '123456789'
                    amount: '3456.23'
                    type: wire_transfer
                    direction: O
                    timestamp: '2022-01-20T08:48:39Z'
                    sender_country: CA
                    receiver_country: US
              Between_2_BBANs_v2:
                value:
                  id: aeio-1234569
                  attributes:
                    sender_name: Footprints on the Moon
                    sender_account: '123456789'
                    receiver_name: Bernadette Rostenkowski
                    receiver_account: '123456789'
                    amount: '3456.23'
                    type: wire_transfer
                    direction: O
                    timestamp: '2022-01-20T08:48:39Z'
                    sender_country: CA
                    receiver_country: US
                    sender_bank_name: Star Bank
                    receiver_bank_name: Gold bank
              To_phone_number:
                value:
                  id: aeio-1234567
                  attributes:
                    amount: '3456.23'
                    type: payment
                    receiver_country: DE
                    receiver_phonenumber: '+491234567'
                    receiver_name: Amy Farrah Fowler
                    timestamp: '2022-01-20T08:48:39Z'
                    direction: O
              From_cashpoint:
                value:
                  id: aeio-1234567
                  attributes:
                    amount: '3456.23'
                    type: deposit
                    cash_point: Seven 11 Pasadena
                    timestamp: '2022-01-20T08:48:39Z'
                    direction: I
              To_wallet_ID:
                value:
                  id: aeio-1234567
                  attributes:
                    amount: '3456.23'
                    type: deposit
                    wallet_id: 12345-12345-12345
                    sender_account: GB12345678
                    sender_name: Stuart Bloom
                    timestamp: '2022-01-20T08:48:39Z'
                    direction: I
              Card_payment:
                value:
                  id: aeio-1234567
                  attributes:
                    amount: '3456.23'
                    type: mcc
                    mcc: '6657'
                    point_of_sale_country: US
                    merchant_details: FACEBK *ADS fb.me/ads IRL
                    receiver_name: FACEBK *ADS
                    timestamp: '2022-01-20T08:48:39Z'
                    direction: O
      responses:
        '200':
          description: Created transaction
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/ApiTransaction
              examples:
                Between_2_IBANs:
                  value:
                    id: aeio-1234567
                    personId: bbt12345
                    attributes:
                      sender_name: Sheldon Cooper
                      sender_account: GB123456789
                      receiver_name: Leonard Hofstadter
                      receiver_account: DE987654321
                      amount: '15678.34'
                      type: wire_transfer
                      direction: I
                      timestamp: '2022-01-20T08:48:39Z'
                Between_2_BBANs_v1:
                  value:
                    id: aeio-1234568
                    personId: bbt12347
                    attributes:
                      sender_name: Footprints on the Moon
                      sender_account: '123456789'
                      receiver_name: Bernadette Rostenkowski
                      receiver_account: '123456789'
                      amount: '3456.23'
                      type: wire_transfer
                      direction: O
                      timestamp: '2022-01-20T08:48:39Z'
                      sender_country: CA
                      receiver_country: US
                Between_2_BBANs_v2:
                  value:
                    id: aeio-1234569
                    personId: bbt12348
                    attributes:
                      sender_name: Footprints on the Moon
                      sender_account: '123456789'
                      receiver_name: Bernadette Rostenkowski
                      receiver_account: '123456789'
                      amount: '3456.23'
                      type: wire_transfer
                      direction: O
                      timestamp: '2022-01-20T08:48:39Z'
                      sender_country: CA
                      receiver_country: US
                      sender_bank_name: Star Bank
                      receiver_bank_name: Gold bank
                To_phone_number:
                  value:
                    id: aeio-1234567
                    personId: bbt12345
                    attributes:
                      amount: '3456.23'
                      type: payment
                      receiver_country: DE
                      receiver_phonenumber: '+491234567'
                      receiver_name: Amy Farrah Fowler
                      timestamp: '2022-01-20T08:48:39Z'
                      direction: O
                From_cashpoint:
                  value:
                    id: aeio-1234567
                    personId: bbt12345
                    attributes:
                      amount: '3456.23'
                      type: deposit
                      cash_point: Seven 11 Pasadena
                      timestamp: '2022-01-20T08:48:39Z'
                      direction: I
                To_wallet_ID:
                  value:
                    id: aeio-1234567
                    personId: bbt12345
                    attributes:
                      amount: '3456.23'
                      type: deposit
                      wallet_id: 12345-12345-12345
                      sender_account: GB12345678
                      sender_name: Stuart Bloom
                      timestamp: '2022-01-20T08:48:39Z'
                      direction: I
                Card_payment:
                  value:
                    id: aeio-1234567
                    personId: bbt12345
                    attributes:
                      amount: '3456.23'
                      type: mcc
                      mcc: '6657'
                      point_of_sale_country: US
                      merchant_details: FACEBK *ADS fb.me/ads IRL
                      receiver_name: FACEBK *ADS
                      timestamp: '2022-01-20T08:48:39Z'
                      direction: O
        '400':
          description: Bad request
          content:
            application/text:
              schema:
                type: string
                description: Error message
        '401':
          description: Unauthorized
          content:
            application/text:
              schema:
                type: string
                description: Error message
        '404':
          description: Person not found
          content:
            application/text:
              schema:
                type: string
                description: Error message
        '422':
          description: Transaction exists
          content:
            application/text:
              schema:
                type: string
                description: Error message
  /v1/persons/{personId}/transactions/{transactionId}:
    get:
      tags:
      - AML
      summary: Fetch transaction by id
      operationId: findTransactionByIdAndPersonId
      parameters:
      - name: personId
        in: path
        description: ID of person
        required: true
        schema:
          type: string
          minLength: 1
      - name: transactionId
        in: path
        description: ID of transaction to return
        required: true
        schema:
          type: string
          minLength: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/ApiTransaction
              examples:
                Between_2_IBANs:
                  value:
                    id: aeio-1234567
                    personId: bbt12345
                    attributes:
                      sender_name: Sheldon Cooper
                      sender_account: GB123456789
                      receiver_name: Leonard Hofstadter
                      receiver_account: DE987654321
                      amount: '15678.34'
                      type: wire_transfer
                      direction: I
                      timestamp: '2022-01-20T08:48:39Z'
                Between_2_BBANs_v1:
                  value:
                    id: aeio-1234568
                    personId: bbt12347
                    attributes:
                      sender_name: Footprints on the Moon
                      sender_account: '123456789'
                      receiver_name: Bernadette Rostenkowski
                      receiver_account: '123456789'
                      amount: '3456.23'
                      type: wire_transfer
                      direction: O
                      timestamp: '2022-01-20T08:48:39Z'
                      sender_country: CA
                      receiver_country: US
                Between_2_BBANs_v2:
                  value:
                    id: aeio-1234569
                    personId: bbt12348
                    attributes:
                      sender_name: Footprints on the Moon
                      sender_account: '123456789'
                      receiver_name: Bernadette Rostenkowski
                      receiver_account: '123456789'
                      amount: '3456.23'
                      type: wire_transfer
                      direction: O
                      timestamp: '2022-01-20T08:48:39Z'
                      sender_country: CA
                      receiver_country: US
                      sender_bank_name: Star Bank
                      receiver_bank_name: Gold bank
                To_phone_number:
                  value:
                    id: aeio-1234567
                    personId: bbt12345
                    attributes:
                      amount: '3456.23'
                      type: payment
                      receiver_country: DE
                      receiver_phonenumber: '+491234567'
                      receiver_name: Amy Farrah Fowler
                      timestamp: '2022-01-20T08:48:39Z'
                      direction: O
                From_cashpoint:
                  value:
                    id: aeio-1234567
                    personId: bbt12345
                    attributes:
                      amount: '3456.23'
                      type: deposit
                      cash_point: Seven 11 Pasadena
                      timestamp: '2022-01-20T08:48:39Z'
                      direction: I
                To_wallet_ID:
                  value:
                    id: aeio-1234567
                    personId: bbt12345
                    attributes:
                      amount: '3456.23'
                      type: deposit
                      wallet_id: 12345-12345-12345
                      sender_account: GB12345678
                      sender_name: Stuart Bloom
                      timestamp: '2022-01-20T08:48:39Z'
                      direction: I
                Card_payment:
                  value:
                    id: aeio-1234567
                    personId: bbt12345
                    attributes:
                      amount: '3456.23'
                      type: mcc
                      mcc: '6657'
                      point_of_sale_country: US
                      merchant_details: FACEBK *ADS fb.me/ads IRL
                      receiver_name: FACEBK *ADS
                      timestamp: '2022-01-20T08:48:39Z'
                      direction: O
        '400':
          description: Invalid ID supplied
        '404':
          description: Person or Transaction not found
    patch:
      tags:
      - AML
      description: Updates transaction. Currently status is the only attribute that can be updated.
      summary: Update transaction
      operationId: updateTransaction
      parameters:
      - name: personId
        in: path
        description: ID of person
        required: true
        example: user-00000009
        schema:
          type: string
          minLength: 1
      - name: transactionId
        in: path
        description: ID of transaction
        required: true
        example: transaction-000000000009
        schema:
          type: string
          minLength: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/ApiUpdateTransaction
      responses:
        '200':
          description: Updated transaction
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/ApiTransaction
        '400':
          description: Invalid input
        '404':
          description: Person or Transaction not found
  /v1/persons/{personId}/statuses:
    get:
      tags:
      - AML
      summary: Fetch history of status changes for the person
      operationId: findStatusesHistory
      parameters:
      - name: personId
        in: path
        description: ID of person
        required: true
        schema:
          type: string
          minLength: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/ApiPersonStatuses
        '400':
          description: Invalid ID supplied
        '404':
          description: Person not found
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: 'In order to use the API, you need to generate client credentials using [Salv UI](https://demo.salv.com/credentials).

        Never share your secret keys. Keep them guarded and secure.


        We use OAuth2 client credentials flow to issue our API tokens.

        By default our API tokens have expiration time of 50 years, so effectively they never expire.

        Please do not make any assumptions about the content of the access_token.

        At the moment we use a JWT token, but it can change to any other string with the future updates.


        An API token can be invalidated using Salv UI by deleting the client credentials that were used to generate the token.


        Please make sure you only request it once per reasonable amount of time,

        as `oauth/token` endpoint has a rate limit of **10 requests per minute** per IP address.


        | Environment | Token URL |

        |-------------|-----------|

        | Production | `https://app.salv.com/oauth/token` |

        | Sandbox | `https://demo.salv.com/oauth/token` |


        Use the token URL matching your selected server environment.

        '
      flows:
        clientCredentials:
          tokenUrl: https://app.salv.com/oauth/token
          x-tokenUrl-sandbox: https://demo.salv.com/oauth/token
          scopes:
            aml: Can use AML API
x-tagGroups:
- name: General
  tags:
  - changelog
  - getting-started
  - data-upload
  - aml
  - note
  - webhooks
  - custom-list-record
  - custom-list-usable-field-public
- name: Monitoring
  tags:
  - monitoring-overview
  - monitoring-checks
  - alert
- name: Screening
  tags:
  - screening-overview
  - screening-checks
  - screening-searches
  - screening-list-groups
  - screening-alerts
- name: Risks
  tags:
  - risk
- name: Alert management
  tags:
  - alerts
  - manual-alerts
- name: Deprecated
  tags:
  - unresolved-alerts
